export const DRIF_CATEGORY_ORDER = ["OFFENSIVE", "DEFENSIVE", "UTILITY"];

export const DRIF_CATEGORY_LABELS = {
    OFFENSIVE: "Ofensywne",
    DEFENSIVE: "Defensywne",
    UTILITY: "Użytkowe",
};

export const DRIF_SIZE_ORDER = ["SUBDRIF", "BIDRIF", "MAGNIDRIF", "ARCYDRIF"];

export const DRIF_SIZE_LABELS = {
    SUBDRIF: "S",
    BIDRIF: "B",
    MAGNIDRIF: "M",
    ARCYDRIF: "A",
};

export const normalizeDrifCategoryKey = (value) => {
    const category = String(value || "")
        .trim()
        .toUpperCase();
    return DRIF_CATEGORY_ORDER.includes(category) ? category : "";
};

const DRIF_BONUS_CATEGORY_FALLBACK = {
    CC_PROTECTION: "DEFENSIVE",
    CRITICAL_DAMAGE_CHANCE_REDUCTION: "DEFENSIVE",
    CRITICAL_DAMAGE_REDUCTION: "DEFENSIVE",
    DAMAGE_REDUCTION: "DEFENSIVE",
    DAMAGE_REDUCTION_CHANCE: "DEFENSIVE",
    DEFENSE_MELEE: "DEFENSIVE",
    DEFENSE_MENTAL: "DEFENSIVE",
    DEFENSE_RANGE: "DEFENSIVE",
    DODGE_CHANCE: "DEFENSIVE",
    DOUBLE_DEFENSE_ROLL_CHANCE: "DEFENSIVE",
    PASIVE_DAMAGE_REDUCTION: "DEFENSIVE",
    PERCENTAGE_DAMAGE_REDUCTION: "DEFENSIVE",
    CRITICAL_CHANCE: "OFFENSIVE",
    DAMAGE_ENERGY: "OFFENSIVE",
    DAMAGE_FIRE: "OFFENSIVE",
    DAMAGE_FROST: "OFFENSIVE",
    DAMAGE_MAGIC: "OFFENSIVE",
    DAMAGE_PHYSICAL: "OFFENSIVE",
    DOUBLE_ATTACK_CHANCE: "OFFENSIVE",
    DOUBLE_HIT_ROLL_CHANCE: "OFFENSIVE",
    HIT_CHANCE_MELEE: "OFFENSIVE",
    HIT_CHANCE_MENTAL: "OFFENSIVE",
    HIT_CHANCE_RANGED: "OFFENSIVE",
    MENTAL_DEFENSE_REDUCTION: "OFFENSIVE",
    DISPELL_CHANCE: "UTILITY",
    MANA_REGEN: "UTILITY",
    MANA_STEAL: "UTILITY",
    MANA_USAGE_REDUCTION: "UTILITY",
    STAMINA_REGEN: "UTILITY",
    STAMINA_USAGE_REDUCTION: "UTILITY",
};

export const resolveDrifCategoryKey = (bonusType, drifBonusCategories = {}) =>
    drifBonusCategories[bonusType] || DRIF_BONUS_CATEGORY_FALLBACK[bonusType] || "";
