spring.datasource.url=jdbc:sqlite:broken_ranks.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=false

spring.jpa.show-sql=true
hibernate.format_sql=true