spring.datasource.url=jdbc:sqlite:broken_ranks.db
spring.datasource.driverClassName=org.sqlite.JDBC

# Kluczowe ustawienia dla SQLite
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# To ustawienie gwarantuje, ?e najpierw zadzia?a schema.sql, potem data.sql
spring.jpa.defer-datasource-initialization=false

# Dialekt (u?yj swojej klasy, je?li j? stworzy?e?, lub usu? t? lini?)
# spring.jpa.database-platform=pl.brokenranks.tool.broken_ranks_tool.config.SQLiteDialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.show-sql=true
hibernate.format_sql=true