spring.profiles.default=local

spring.datasource.driverClassName=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

optimizer.beam-search-steps=55000
optimizer.maximization-search-steps=20000
optimizer.refinement-search-steps=25000
optimizer.max-concurrent-runs=1
spring.jpa.defer-datasource-initialization=false
